#%RAML 1.0 Trait
queryParameters:
      employeeID:
        required: true
        type: integer
        example: 12345
      employeeStatus:
        required: true
        type: string
        example: "A"